### ISSUE TITLE
Include Markitdown?

### ISSUE THREAD

**Issue by atomic1fire** [mundimark/awesome-markdown#11]
https://github.com/bambax/markitdown.medusis.com

http://markitdown.medusis.com/

As I understand it, Markitdown is built on javascript but runs entirely clientside. The idea being it allows anyone to convert rich text to markdown with copy and paste.

I don't know the developer but I've mainly used it to convert rich text to something I could paste on reddit with most of the formatting intact.

**Comment by geraldb** [comment]
@atomic1fire  You're welcome to add Markitdown to the page. Cheers.
