### ISSUE TITLE
Add Links to Awesome Lists & Other Similar Projects

### ISSUE THREAD

**Issue by tajmone** [mundimark/awesome-markdown#13]
Hi @mundimark,

great repo this one! I'm linking it in my own markdown project:

https://github.com/tajmone/markdown-guide#awesome-markdown

Why not add links to Awesome Markdown lists and other similar projects? If we all link to each other's projects we make it easier for users to find markdown resources.

**Comment by geraldb** [comment]
@tajmone  Good point. All (alternative) markdown lists get linked and listed in the [NOTES.md	](https://github.com/mundimark/awesome-markdown/blob/master/NOTES.md) page. If yours is missing, please add it. Cheers.
