### ISSUE TITLE
markedpp - markdown pre-processor

### ISSUE THREAD

**Issue by commenthol** [mundimark/awesome-markdown#22]
Hi @geraldb,

I'm the author of `markedpp` https://github.com/commenthol/markedpp a markdown pre-processor which add some enhancements to markdown. 

It adds features like table-of-contents, numbered headings, reference lists  as well as including other files.

The output itself is markdown again but adapted to the later markdown processor.

Maybe the tool is something you'd like to add to your awesome list of markdown tools. 

If this is the case then `md-fileserver` https://github.com/commenthol/md-fileserver may be of interest as well.

Thanks.

**Comment by geraldb** [comment]
Yes, please do. It's D-I-Y (do-it-yourself). Your update / pull request more than welcome. Greetings from Vienna. Cheers.
